# Generated by Django 4.1 on 2022-09-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlist',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='release_date',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='review',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='watched',
            field=models.IntegerField(default=0),
        ),
    ]
